### PR TITLE
Make getting the weather follow the architecture

### PR DESCRIPTION
**Pull request by triallax**
~~APK: [app-release.apk.zip](https://github.com/CentaurusApps/clima/files/5894672/app-release.apk.zip)~~ 
~~[APK](https://github.com/CentaurusApps/clima/files/5937190/clima.apk.zip)~~
[APK](https://github.com/CentaurusApps/clima/files/5978108/app-release.apk.zip)

### CODE REVIEW

**Review by prestosole — DISMISSED** [review]

**Comment by prestosole** [comment]
- [x] Add "Invalid city name" and "Can't connect to server" failures.
- [x] `onEditingComplete`  not working on city text field.
- [x] Replace going back to the loading screen each time the refresh button or the search button is pressed with a circular progress indicator.
- [x] Snack bar doesn't show up again when pressing the `retry`  button and without connection.
- [x] When pressing "get weather" or enter in the city screen, it takes a bit for the loading screen to appear.
- [x] Show errors in weather screen in case of failure

**Comment by triallax** [comment]
Fixed 2 and 4. [APK](https://github.com/CentaurusApps/clima/files/5919409/clima.apk.zip)

**Comment by triallax** [comment]
Fixed issue 3. [APK](https://github.com/CentaurusApps/clima/files/5937190/clima.apk.zip)

**Comment by triallax** [comment]
Fixed the rest of the issues. [APK](https://github.com/CentaurusApps/clima/files/5978108/app-release.apk.zip)

**Pull request merged**
