### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by prestosole**

### CODE REVIEW

**Comment by triallax** [comment]
I honestly don't think this is necessary right now. If problems crop up, then I think this might be re-considered, but it's not necessary now. Adding a code of conduct just for the sake of it is never a good thing IMO.

**Comment by prestosole** [comment]
It's not a matter of necessity.

**Comment by triallax** [comment]
Care to elaborate?

**Comment by prestosole** [comment]
It's is recommended by the community standards whether it is necessary or not. It's a good behavior anyway.

**Comment by prestosole** [comment]
Also, how do you define "necessary" here?

**Comment by triallax** [comment]
You don't follow "best" practices just because some community standard recommends so. I don't want to see this merged unless for a good, concrete reason.

**Comment by prestosole** [comment]
It's for a reason: define our pledge, standards, scop, and enforcement guidelines.

Isn't that enough of a reason?

**Comment by triallax** [comment]
Ok, fine, but not this specific document; I don't agree with some of the things listed here. We should write our own instead.

**Comment by prestosole** [comment]
I don't mind, but can you point those changes out?

**Comment by triallax** [comment]
I'm not suggesting editing this document; I want us to start from scratch. We can discuss this in a separate issue.

**Review by triallax — APPROVED** [review]
I still think this is not necessary right now, but oh well.

**Comment by smaragdus** [comment]
I was browsing [F-Droid](https://f-droid.org/en/) for weather apps and I came upon [Clima](https://f-droid.org/en/packages/co.prestosole.clima/) but before installing it I chose to have a look at its [repository](https://github.com/Lacerte/clima) only to find out that the project was contaminated by [CODE_OF_CONDUCT](https://github.com/Lacerte/clima/blob/master/CODE_OF_CONDUCT.md) so I will not install the app as I do not want to use apps by developers who are stupid enough to push communism by the backdoor. The good thing is that I also discovered by chance that an app I had been using- [Tasks](https://github.com/tasks/tasks), has also been contaminated with the abominable [CODE_OF_CONDUCT](https://github.com/tasks/tasks/blob/main/CODE_OF_CONDUCT.md) so I will remove it for good as I do not submit to the tyranny of the idiots.

**Comment by triallax** [comment]
At first I blocked you, but now, I think that was in haste and not in accordance with the code of conduct (which, though I disagree with, I have to follow as long as it exists); for that I apologize. I am willing to discuss this matter with you. However, if you continue with the insults and negative tone, I am afraid I may have to resort to stricter punishment.

In any case, care to elaborate your comment? You don't provide any specific reasons why the code of conduct is "communist" (I think that's what you're saying); in addition you seem to fail to realize that the code of conduct applies not to the users, but to the people who participate in the project's community.

**Comment by abaker** [comment]
@smaragdus Assuming you find [F-Droid's code of conduct](https://f-droid.org/en/docs/Code_of_Conduct/) to be acceptable, I'm curious what objections you have to the codes of conduct [provided by GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)?

**Pull request merged**
